INHERIT: mkdocs.yml
site_dir: local_docs
# Make building work locally, without any setup

# Must be mkdocs, readthedocs, or a theme with local file support
# Happens to = mkdocs.yml right now by coincedence
theme:
  name: readthedocs
  prev_next_buttons_location: none
  navigation_depth: 6

# Recommended at https://www.mkdocs.org/user-guide/configuration
site_url: ""
use_directory_urls: false
plugins: []

